DROP TABLE CUSTOMER IF EXISTS;
CREATE TABLE CUSTOMER (
    EMAIL varchar(255),
    ID long,
    FIRSTNAME varchar(255),
    LASTNAME varchar(255),
    PHONE varchar(255),
    PASSWORD varchar(255)
);

DROP TABLE PRODUCT IF EXISTS;
DROP TABLE PRICE IF EXISTS;
DROP TABLE STORE IF EXISTS;
DROP TABLE CURRENCY IF EXISTS;
DROP TABLE CATALOG IF EXISTS;

CREATE TABLE CATALOG(ID VARCHAR(255) PRIMARY KEY,
   NAME VARCHAR(255));

CREATE TABLE CURRENCY(ID VARCHAR(255) PRIMARY KEY,
   SYMBOL VARCHAR(255));

CREATE TABLE STORE(ID VARCHAR(255) PRIMARY KEY,
   NAME VARCHAR(255), CATALOGID VARCHAR(255), FOREIGN KEY (CATALOGID) REFERENCES CATALOG(ID),
CURRENCYID VARCHAR(255), FOREIGN KEY(CURRENCYID) REFERENCES CURRENCY(ID));

CREATE TABLE PRICE(ID VARCHAR(255) PRIMARY KEY,
   VALUE VARCHAR(255), CURRENCYID VARCHAR(255), FOREIGN KEY(CURRENCYID) REFERENCES CURRENCY(ID));

CREATE TABLE PRODUCT(ID VARCHAR(255) PRIMARY KEY,
   NAME VARCHAR(255), CATALOGID VARCHAR(255), FOREIGN KEY (CATALOGID) REFERENCES CATALOG(ID),
PRICEID VARCHAR(255), FOREIGN KEY(PRICEID) REFERENCES PRICE(ID), IMAGE varbinary (max));